### ISSUE TITLE
handshake failure when fetching database files

### ISSUE THREAD

**Issue by hasitha** [elixytics/ref_inspector#1] opened 2016-11-24 16:27 UTC
In version 0.13.0, after running `mix ref_inspector.yaml.download`, I get the error:

`[error] SSL: :certify: tls_connection.erl:688:Fatal error: handshake failure - malformed_handshake_data`

**Comment by mneudert** [comment] 2016-11-24 20:21
I think this error is related to `:hackney` itself: https://github.com/benoitc/hackney/issues/362

However I was not able to reproduce this error even with the newest hackney release (`1.6.3`). That is probably related to my environment being completely different from what is described in aforementioned issue. According to comments there it should help to downgrade to version `1.6.1` in `mix.exs`.

Could you try that?

**Comment by hasitha** [comment] 2016-11-29 15:05
Sorry about the late reply.

With 1.6.3, I'm still running into the issue, but with 1.6.1 I'm not.

**Comment by mneudert** [comment] 2016-11-29 18:34
Have not been able to reproduce that with multiple Erlang/Elixir combinations. At least not on non-MacOS-systems. But if downgrading hackney "fixes" your problem that seems to be the way to go for now.

Perhaps there is some configuration value one can pass to hackney using `:http_opts` but that is pure speculation at this point.

We could leave this issue open as some sort of reminder until a new hackney version is released.

**Comment by mneudert** [comment] 2016-12-28 11:13
Hackney has released a new version (`1.6.5`) last week. Could you give that one a shot and see if your problem is solved?

**Comment by mneudert** [comment] 2017-02-12 15:37
I am closing this as it seems to be properly solved with the last hackney release.

**Closed as completed by mneudert** 2017-02-12 15:37 UTC
